Traceback (most recent call last):
  File "<ipython-input-5-ef71c3774499>", line 3, in <module>
    raise Exception('ini errornya')
Exception: ini errornya
